[Web] animation & dialog UI
OtterClam/otter-frontend pull request #12
Opened 2021-12-03 14:37 UTC by michian

2021-12-04 02:08 UTC, otterclamking requested changes

2021-12-04 02:08 UTC, otterclamking commented on src/components/Button/ActionButton.tsx
> +function ActionButton(props: any) {
need to define props interface

2021-12-05 04:36 UTC, otterclamking commented
Hey @michian The dialog close button is wrong on Firefox 95.0b12 (64-bit).

![CleanShot 2021-12-05 at 12 34 00@2x](https://user-images.githubusercontent.com/93432230/144733675-3582d874-579a-4b16-8240-4c0a981bfa6c.jpg)

About the success dialog, it works for the bonding. I suggest separating the bond/stake integration into two PRs. 

Then we can merge the bond success dialog first.

2021-12-05 08:00 UTC, michian commented
Hey @otterclamking, I pushed the changes on the close button for firefox.

About the stake/unstake not working, I can't separate them because I changed a function used by all action buttons.

I tried to stake/unstake with my own wallet and It's working fine. No changes on my side.
![image](https://user-images.githubusercontent.com/23115995/144738325-21c7cf1a-8ff1-445f-b748-663835b5cf5a.png)

2021-12-05 12:48 UTC, michian commented
For some reason stake/unstake in getting stuck when using local node but works fine when using polygon network.

2021-12-06 10:58 UTC, otterclamking approved these changes

2021-12-06 10:58 UTC, merged